language: python
python:
  - 3.5
branches:
  only:
    - master
services:
  - docker
env:
  - DOCKER_BUILD_FLAGS="--pull --no-cache"
sudo: required
cache: pip
script:
  - make test
after_success:
  - make upload-coverage
